language: go

go:
  - 1.8
before_install:
  - wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby ruby-dev ubuntu-dev-tools rpm
script:
  - cd ../../ && mv fdns grafana && cd grafana/grafana
  - go run build.go build package
